### ISSUE TITLE
Is it possible to specify the collection_method for a subscription when checkout

### ISSUE THREAD

**Issue by shd101wyy** [stripe-samples/checkout-single-subscription#18]
Is it possible to specify the `collection_method` for a subscription when checkout?  
I see that it is `charge_automatically` by default, is it possible to set `collection_method` to `send_invoice` when we create checkout session?
Thank you.

**Comment by thorsten-stripe** [comment]
Sorry for the delay, for questions about your integration please use our technical chat on IRC: https://webchat.freenode.net/#stripe
