### ISSUE TITLE
Add error handling to Java server example for /create-checkout-session

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe-samples/checkout-single-subscription#21]
# Bug report

## Describe the bug

When you create a checkout session without a PriceID, the server should respond with a 400 status code and 

```json
{
  error: {
    message: "some message"
  }
}
```

Where "some message" is the result of `e.getMessage()`

**Comment by shingkid** [comment]
Hi there.

It's my first time trying my hand at open source, so I would be grateful for any help I can get!

Would `/create-checkout-session` essentially look something like this?
```Java
try {
    // Code block for creating a new checkout session for the order
} catch (Exception e) {
    Map<String, Object> responseError = new HashMap<>();
    responseError.put("error", Collections.singletonMap("message", e.getMessage()));
    response.body(gson.toJson(responseError));
    response.status(400);
    return "";
}
```

**Comment by cjavilla-stripe** [comment]
yeah that seems good! :) thanks!

**Comment by cjavilla-stripe** [comment]
fails correctly now. Closing.
