### ISSUE TITLE
handleFetchResult not used in checkout-single-subscription client

### ISSUE THREAD

**Issue by ekw** [stripe-samples/checkout-single-subscription#236]
# Bug report

## Describe the bug
The variable handleFetchResult (at https://github.com/stripe-samples/checkout-single-subscription/blob/master/client/script.js#L12) is not used anywhere.

## Expected behavior

Expect this variable to be used somewhere, perhaps in catch block for the fetch.

**Comment by cjavilla-stripe** [comment]
Thank you! Just pushed a fix. 🙌
