### ISSUE TITLE
Add go / dotnet to .cli.json

### ISSUE THREAD

**Issue by cjavilla-stripe** [stripe-samples/checkout-single-subscription#25]
We recently added go and dotnet server languages and need to update the cli.json file to include these.

**Comment by anuragsati** [comment]
Hello! can i take this?

**Comment by cjavilla-stripe** [comment]
go for it @anuragsati !

Thank you!!

**Comment by cjavilla-stripe** [comment]
let me know if you have any questions :)

**Comment by anuragsati** [comment]
I need to change `"servers": ["java", "node", "php-slim", "php", "python", "ruby"]` to `"servers": ["java", "node", "php-slim", "php", "python", "ruby", "dotnet", "go"]` right?

**Comment by cjavilla-stripe** [comment]
correct :)

**Comment by anuragsati** [comment]
Thanks for your help. I will get it done
