### ISSUE TITLE
PHP Demo's "shared.php" file missing (again)

### ISSUE THREAD

**Issue by inclu-cat** [stripe-samples/checkout-single-subscription#288]
I have [the same problem ](https://github.com/stripe-samples/checkout-single-subscription/issues/46#issue-771485940)that @jackcrane had. He seems to have found the "shared.php" but now the file is no longer there. 
Can anyone let me know where the file is?

**Comment by cjavilla-stripe** [comment]
@inclu-cat sorry for any confusion. That file shouldn't be needed. It was used by get-checkout-session.php, which also wasn't used by the demo so I'm removing that file too. Thanks!
