### ISSUE TITLE
obvious mistake or is that a deliberate choice behind the screen 

### ISSUE THREAD

**Issue by v2lrf** [stripe-samples/checkout-single-subscription#3]
hey, I agree that it's an obvious mistake but is there any other valid reason or serious reason why the amount is different from the index page to the checkout page?  

plan 5$ week become  5$ /month
plan 12$ week become 15$/month

I guess that this is just a parameter inside dashboard wrongly setup

**Comment by ctrudeau-stripe** [comment]
Hello, it was a typo on the index.html pages. I've corrected it and changed the demo. You should see the $14 subscription redirects to checkout as $14 now. Thank you!
