### ISSUE TITLE
How to backdate and postdate the start of a subscription with the new checkout?

### ISSUE THREAD

**Issue by WayneUong** [stripe-samples/checkout-single-subscription#37]
Hello. We need to handle these 2 scenarios:

1. Postdate a subscription: save the card info, charge the first payment instantly, but only start the subscription in the future.
E.g, user pays first payment on Dec 1 2020, but subscription only starts on Jan 1 2021, and the next payment will be on Jan 1 2022.

2. Backdate a subscription: save the card info, charge the first payment instantly, starts the subscription in the past.
E.g, user pays first payment on Feb 1 2020, but subscription actually started on Jan 1 2020, and the next payment will be on Jan 1 2021.

With the old legacy charge/subscription API, we were able to achieve these using one time charges and set future start date for subscription. These cases are very common in membership payments that do not offer proration (proration in full).

How can we address these cases? Thank you!

**Comment by cjavilla-stripe** [comment]
Hey @WayneUong. Thanks for reaching out. We're not able to provide support here only bug reports about the sample. Can you reach out to support.stripe.com/contact or the engineers on IRC in Freenode #stripe?
