### ISSUE TITLE
The client

### ISSUE THREAD

**Issue by antoineChoite** [stripe-samples/checkout-single-subscription#41]
# Bug report

## Describe the bug

How to update the home page with Stripe.

I changed the value in .env file, but the price in home page don't change 

Is it normal ? if yes what can I do ?

PS : When I click on the price button the redirection works and the price in payement page is good, but not in home page.

**Comment by cjavilla-stripe** [comment]
Hey @antoineChoite,

Thanks for reaching out. The dollar amounts shown on the front end are hard coded in `client/index.html` so that's expected.
