### ISSUE TITLE
Stripe session customer info not being retrieved despite successful webhook

### ISSUE THREAD

**Issue by DaniyalDhz** [stripe-samples/checkout-single-subscription#43]
Hi there,
I have the following code taken from multiple flask subscription docs on the web. Everything works perfectly fine, **however**, `stripeData = event["data"]["object"]`looks like its **not** returning the customer info, as "didn't get stored" gets return in the success endpoint. I am so confused why this is the case when the web hook is successful per the payments going through in the dashboard and when connecting to stripe-cli, the customer info even gets shown. However, by its own it doesn't. Would really appreciate some clarity.

```
stripe_keys = {
    "secret_key":'sk_test_5...GKIv8T67w0f8000ypWZx9om',
    "publishable_key": 'pk_test_51Hhm...X6q2FLqW',
    "price_id": 'price_1HhmCyBBlU..f',
    "endpoint_secret":'whsec_lFkitrmzG...u0PbD4riv7'
}
stripe.api_key = stripe_keys["secret_key"]

@blueprint.route("/stripe_webhook", methods=["POST"]) 
def stripe_webhook():
    # print("Webhook called ")
    payload = request.get_data(as_text=True)
    sig_header = request.headers.get("Stripe-Signature") 
    event = None
    try:
        event = stripe.Webhook.construct_event(
            payload, sig_header, stripe_keys["endpoint_secret"]
        )
    except ValueError as e:
        return "Invalid payload", 400
    except stripe.error.SignatureVerificationError as e:
        # Invalid signature
        return "Invalid signature", 400

    if event["type"] == "checkout.session.completed":
        try:
            stripeData = event["data"]["object"]
            stripe_customer_id = stripeData['customer']
            stripe_subscription_id = stripeData['subscription']
            user = User.query.filter_by(id=str(session['id'])).first()
            user = User(stripeSubscripstionId= stripe_subscription_id, stripeCustomerId= stripe_customer_id)
            db.session.add(user)
            db.session.commit()
        except:
            print('FAILED TO WORK') #doesn't get returned
    return {}

@blueprint.route("/config")
def get_publishable_key():
    stripe_config = {"publicKey": stripe_keys["publishable_key"]}
    return jsonify(stripe_config)

@blueprint.route("/success")
def success():
    print('session id is')
    print(session['id'])
    user = User.query.filter_by(id=str(session['id'])).first()
    if user.stripeSubscriptionId:
        return render_template("/General/success.html")
    return "didn't get stored"

@blueprint.route("/create-checkout-session") 
def create_checkout_session():
    domain_url = "http://localhost:5000/"
    stripe.api_key = stripe_keys["secret_key"]
    # User.query.filter_by(id=session['id']).first() 
    try:
        checkout_session = stripe.checkout.Session.create(

            client_reference_id=User.id,
            success_url=domain_url + 'success?session_id={CHECKOUT_SESSION_ID}',
            cancel_url=domain_url + "cancel", 
            payment_method_types=["card"],
            mode="subscription",
            line_items=[
                {
                    "price": stripe_keys["price_id"],
                    "quantity": 1,
                }
            ]
        )
        return jsonify({"sessionId": checkout_session["id"]})
    except Exception as e:
        return jsonify(error=str(e)), 403

```
## System information

- OS: macOS BigSur
- Browser (if applies) Safari
- Server environment py 3.9

**Comment by cjavilla-stripe** [comment]
Hey @DaniyalDhz Thanks for reaching out. Sorry to hear the webhook payload doesn't include the expected data. Can you share the specific event ID (Its a string ID that starts with `evt_`) so we can take a closer look?

**Comment by DaniyalDhz** [comment]
Hi @cjavilla-stripe 
Thanks for getting back!
Sure so one of them is "evt_1HtJXvBBlUfRTiTYG4CrSAwb".

**Comment by cjavilla-stripe** [comment]
Hey @DaniyalDhz.

I just checked the logs for event and I do see the ID of the customer in that request body. Can you share more details about how this error is manifesting and what error output you're seeing?

**Comment by DaniyalDhz** [comment]
Hi @cjavilla-stripe !
Thanks for getting back,

Yeah I do see the customer's info in JSON format on my (Stripe develops console) too w/o any error displayed on the server. However, I don't get the customer info JSON from `stripeData = event["data"]["object"]` to retrieve and store the necessary information unless I run stripe-cli web hook listener simultaneously which I don't think would be possible in production environment.

**Comment by cjavilla-stripe** [comment]
Hey @DaniyalDhz In production, you would configure the webhook endpoint in your Stripe dashboard to point to your production server. There's more info about this here: https://stripe.com/docs/webhooks/go-live

**Comment by DaniyalDhz** [comment]
Hey @cjavilla-stripe!
That definitely makes sense!
So if I still want to retrieve user's info in _development environment_ just to make sure everything is working fine, is my only bet a stripe-webhook listener cli to be run at the same time or can I add 127.0.0.1:5000/ to it the stripe's webhook endpoint too?

**Comment by DaniyalDhz** [comment]
Hey @cjavilla-stripe!
That definitely makes sense. I didn't know I had to fire another stripe cli terminal every-time for development environment. Nonetheless, I installed the stipe cli via `https://github.com/stripe/stripe-cli/releases/tag/v1.5.5` and unzipped it. However, I got:
```
stripe
zsh: command not found: stripe
```
so then I tried your way of installing with home brew but unfortunately:
```
Homebrew is not (yet) supported on ARM processors!
Rerun the Homebrew installer under Rosetta 2.
If you really know what you are doing and are prepared for a very broken
experience you can use another installation option for installing on ARM:
 https://docs.brew.sh/Installation 
```

**Comment by DaniyalDhz** [comment]
Hey @cjavilla-stripe !

That definitely makes sense! I was just hoping for a shorter version w/o having to fire up stripe cli for dev each time. Nonetheless, thank you for helping me :))
