### ISSUE TITLE
How to make a referral program with stripe subscription

### ISSUE THREAD

**Issue by DaniyalDhz** [stripe-samples/checkout-single-subscription#45]
Hi there, 
My question is more business related than code:

In my app, I'd like to give an extra week of subscription if a user referred someone to the app. 
My question:

1. Does stripe provide any referral program apis? to handle the referral program backend by itself just like with checkout. I wasn't able to find any.
2. if not, I would construct the program, in such logic on my own end:
Attach the inviter's username to the end of the URL, if the invitee logs in, a week gets taken of from inviter's subscription time in db. My only problem is that how will I make this manual update to the user's stripe info on your db?

**Comment by cjavilla-stripe** [comment]
Hey @DaniyalDhz Thanks for reaching out. We're not able to handle support questions through GitHub issues. Instead can you ask your questions directly to support: support.stripe.com/contact or on IRC in the Freenode network in the #stripe channel?
