### ISSUE TITLE
PHP Demo's "shared.php" file missing

### ISSUE THREAD

**Issue by jackcrane** [stripe-samples/checkout-single-subscription#46]
Many of the files in the server/PHP demonstration of this repo are including a "shared.php" file, but there is not one anywhere in the repo.

Some of the files that include it are:
`server/php/public/config.php`
`server/php/public/get-checkout-session.php`
`server/php/public/webhook.php`
`server/php/public/create-checkout-session.php`

**Comment by jackcrane** [comment]
EDIT: I am stupid...

https://github.com/stripe-samples/checkout-single-subscription/blob/master/server/php/public/shared.php

**Comment by jackcrane** [comment]
@inclu-cat sorry i deleted that code years ago.

**Comment by inclu-cat** [comment]
@jackcrane Oh, I see. Thanks!
