### ISSUE TITLE
https://github.com/kiwiirc/kiwiirc.wiki.git

### ISSUE THREAD

**Issue by salwa445** [stripe-samples/checkout-single-subscription#54]
# Bug report

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
@salwa445 please provide context to your issue.
