### ISSUE TITLE
No StripeOptions class

### ISSUE THREAD

**Issue by LeighHuff** [stripe-samples/checkout-single-subscription#57]
# Bug report

## Sample Startup.cs Breaks

The sample Startup.cs code references a <StripeOptions> type that does not exist in the namespaces or libraries referenced in the using statements.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. Copy the code into an actual file and see the error

## System information

- OS: [e.g. macOS, Windows]
- Browser (if applies) [e.g. chrome, safari]
- Server environment [e.g. Go, Java, Node, PHP, Python, Ruby, TypeScript]

**Comment by cjavilla-stripe** [comment]
Hey @LeighHuff, 

Sorry for any confusion. The file is right here: https://github.com/stripe-samples/checkout-single-subscription/blob/master/server/dotnet/Configuration/StripeOptions.cs 

It should be loaded as part of the demo.

**Comment by LeighHuff** [comment]
Thanks CJ!
