### ISSUE TITLE
Domain redirect

### ISSUE THREAD

**Issue by matteolavaggi** [stripe-samples/checkout-single-subscription#6]
var redirectToCheckout = function(planId) {
        // Make the call to Stripe.js to redirect to the checkout page
        // with the current quantity
        stripe
          .redirectToCheckout({
            items: [{ plan: planId, quantity: 1 }],
            successUrl:
              **"https://"** + DOMAIN + "/success.html?session_id={CHECKOUT_SESSION_ID}",
            cancelUrl: **"https://"** + DOMAIN + "/canceled.html"
          })
          .then(handleResult);
      };

MISS protocol in default client only redirect (in javascript)

**Comment by ultraGentle** [comment]
Thank you, this helped me.

**Comment by adreyfus-stripe** [comment]
Thanks for reporting, just updated the sample to reflect this.
