### ISSUE TITLE
Client-only in codesandbox.io

### ISSUE THREAD

**Issue by cwartel** [stripe-samples/checkout-single-subscription#7]
Hello,
I would like to set up a codesandbox.io client only example to share it.
I guess the server part with the start command in the package.json would not be needed.
Can you help me on that one ?

**Comment by adreyfus-stripe** [comment]
@cwartel I believe codesandbox currently doesn't support running static sites but you can use another service like glitch.com or netlify.com to host your site. 

Hope that helps!

**Comment by cwartel** [comment]
thank you for your answer @adreyfus-stripe I ended up setting it up by copying the files.
