### ISSUE TITLE
Can't redirect to Localhost on success, preventing local testing

### ISSUE THREAD

**Issue by ultraGentle** [stripe-samples/checkout-single-subscription#8]
Hello, the client-only integration is great!  
I'm running into a bug (maybe?) when attempting to test this locally.  

**To reproduce**
1. change the `successURL:` to  `"https://localhost:5000" + "?session_id={CHECKOUT_SESSION_ID}"`,  
2. go through checkout  successfully, using a Test Card
3. see error in browser `This site can’t provide a secure connectionlocalhost sent an invalid response.
ERR_SSL_PROTOCOL_ERROR`

This seems to be a bug, because when loading Checkout locally, it simply issues a warning in the console `You may test your Stripe.js integration over HTTP. However, live Stripe.js integrations must use HTTPS.`

**Current Workaround**
I've created a live testing environment, but this is extremely slow to test, and hard to debug via logging, because any change requires a redeploy.  Being able to use Localhost would 
greatly speed up the dev process, on both counts (speed and readability).  

**Question**
If this is an intentional feature, is there a recommended workaround to serve Localhost over https?  (I did due-diligence Google this, but most solutions are more involved than someone using the client-only integration is probably comfortable with!  So just checking here, first.)

**Additional Information**
Not sure if it's relevant, but I'm using the Firebase local emulator to locally serve and test my web app.  

Thanks!

**Comment by adreyfus-stripe** [comment]
@ultraGentle At the moment we don't have the best guidance for testing client-only Checkout locally, and as you rightly called out that some of the ways describe online aren't very straightforward. 

I've always had the easiest time using python's SimpleHTTPServer to quickly spin up a lightweight server for my static samples, as described here: https://gist.github.com/jgravois/5e73b56fa7756fd00b89#simplehttpserver-a-pythonic-approach, e.g.

```
cd client-only/client
python -m http.server 5000
```

And then I test over http to make sure everything works before deploying.

**Comment by adreyfus-stripe** [comment]
@ultraGentle Delayed response but we added a way to use the Stripe CLI to easily serve static files when testing client-only Checkout integrations. This might not help you at the moment but if you run 

```
stripe serve
```

from the root of your project it will spin up a simple server to serve your static assets. More on that feature here, thanks for indirectly suggesting! https://github.com/stripe/stripe-cli/releases/tag/v1.3.0

**Comment by ultraGentle** [comment]
@adreyfus-stripe Thanks for following up, and being receptive!
